coslr: true
criterions:
  PerformanceLoss:
    def_file: ./imagenet_inat/loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory: {centroids: false, init_centroids: false}
model_dir: ./data
networks:
  classifier:
    def_file: ./imagenet_inat/models/DotProductClassifier.py
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0001}
    params: {dataset: iNaturalist18, feat_dim: 2048, log_dir: ./data,
      num_classes: 8142, stage1_weights: false}
  feat_model:
    def_file: ./imagenet_inat/models/ResNet50Feature.py
    fix: true
    optim_params: {lr: 0.2, momentum: 0.9, weight_decay: 0.0001}
    params: {dataset: iNaturalist18, dropout: null, log_dir: ./data,
      stage1_weights: false, use_fc: false, use_selfatt: false}
shuffle: true
training_opt:
  backbone: resnet50
  batch_size: 512
  dataset: iNaturalist18
  display_step: 10
  feature_dim: 2048
  log_dir: ./data
  log_root: ./data
  num_classes: 8142
  num_epochs: 30
  num_workers: 12
  open_threshold: 0.1
  sampler: {def_file: ./imagenet_inat/data/ClassAwareSampler.py, num_samples_cls: 4, type: ClassAwareSampler}
  scheduler_params: {gamma: 0.1, step_size: 10}
  stage: resnet50_crt_uni2ban_ssp_moco
  sub_dir: clslearn
